plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

repositories {
    maven {
        name = 'nyon'
        url = uri('https://repo.nyon.dev/releases')
        content { includeGroup('dev.nyon') }
    }
}

dependencies {
    implementation("dev.nyon:KotlinLangForge:${klf_version}")
}

sourceSets {
    gametest {
        compileClasspath += sourceSets.main.compileClasspath + sourceSets.main.output
        runtimeClasspath += sourceSets.main.runtimeClasspath + sourceSets.main.output
    }
}

configurations {
    commonGametest { canBeResolved = true }
    commonGametestClasses { canBeResolved = true }
}

dependencies {
    commonGametest(project(path: common_project.path, configuration: 'commonGametest'))
    commonGametestClasses(project(path: common_project.path, configuration: 'commonGametestClasses'))
}

sourceSets.gametest.compileClasspath += configurations.commonGametestClasses

tasks.named('compileGametestKotlin') {
    dependsOn(configurations.commonGametest)
    source(configurations.commonGametest.asFileTree.matching { include '**/*.kt' })
}

neoForge {
    version = neoforge_version

    def at = common_project.file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_namespace)
            ideName = "NeoForge ${it.name.capitalize()}"
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file('runs/client'))
        }
        server {
            server()
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
        gametest {
            type = 'gameTestServer'
            gameDirectory = this.mkdir(this.file('runs/gametest'))
        }
        data {
            clientData()
            gameDirectory = this.mkdir(this.file('runs/data'))
            programArguments.addAll '--mod', project.mod_id, '--all',
                    '--output', file('src/generated/resources/').absolutePath,
                    '--existing', file('src/main/resources/').absolutePath
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet sourceSets.gametest
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements'].each { variant ->
    configurations.named(variant) {
        attributes { attribute(loaderAttribute, 'neoforge') }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named(variant) {
            attributes { attribute(loaderAttribute, 'neoforge') }
        }
    }
}
